EmployeeManegementApp/EmployeeManagementWebUI/Controllers/SCRN0000/SCRN0000Controller.cs
using Microsoft.AspNetCore.Mvc;

namespace EmployeeManagementWebUI.Controllers.SCRN0000
{
    /// <summary>
    /// 社員管理システムTOP コントローラ
    /// </summary>
    /// <remarks>
    /// 社員管理システムTOP コントローラ
    /// </remarks>
    public class SCRN0000Controller : Controller
    {
        #region === 初期表示 ===

        /// <summary>
        /// 初期表示
        /// </summary>
        /// <remarks>
        /// イベント名：社員管理システムTOP画面初期表示
        /// </remarks>
        /// <returns>ActionResult</returns>
        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        #endregion
    }
}

EmployeeManegementApp/EmployeeManagementWebUI/Controllers/SCRN0001/SCRN0001Controller.cs
using EmployeeManagementWebUI.Helper;
using Microsoft.AspNetCore.Mvc;

namespace EmployeeManagementWebUI.Controllers.SCRN0001
{
    /// <summary>
    /// 社員管理システムメニュー　コントローラー
    /// </summary>
    /// <remarks>
    /// 社員管理システムメニュー　コントローラー
    /// </remarks>
    [Route("/employee/menu")]
    public class SCRN0001Controller : Controller
    {
        /// <summary></summary>
        /// <remarks></remarks>
        private readonly IEV0001Helper _ev0001Helper = null;

        /// <summary>
        /// コンストラクタ
        /// </summary>
        /// <remarks>
        /// DIの実施
        /// </remarks>
        public SCRN0001Controller(IEV0001Helper ev0001Helper)
        {
            _ev0001Helper = ev0001Helper;
        }

        /// <summary>
        /// 初期表示
        /// </summary>
        /// <remarks>
        /// イベント名：社員管理システムメニュー画面初期表示
        /// </remarks>
        /// <returns>ActionResult</returns>
        [Route("")]
        [HttpGet]
        public IActionResult Index()
        {
            // 初期化
            var viewModelDto = _ev0001Helper.Init();
            return View(viewModelDto);
        }
    }
}

EmployeeManegementApp/EmployeeManagementWebUI/Controllers/SCRN0002/SCRN0002Controller.cs
using EmployeeManagementWebUI.Helper;
using EmployeeManagementWebUI.ViewModel.SCRN0002;
using Microsoft.AspNetCore.Mvc;
using System.Linq;

namespace EmployeeManagementWebUI.Controllers.SCRN0002
{
    /// <summary>
    /// 社員登録画面　コントローラー
    /// </summary>
    /// <remarks>
    /// 社員登録画面　コントローラー
    /// </remarks>
    [Route("/employee/entry")]
    public class SCRN0002Controller : Controller
    {
        #region === 定数 ===

        /// <summary>コントローラ名：社員管理システムメニュー</summary>
        /// <remarks>コントローラ名：社員管理システムメニュー</remarks>
        private const string CONTROLLER_NAME_MENU = "SCRN0001";

        /// <summary>コントローラ名：社員管理完了</summary>
        /// <remarks>コントローラ名：社員管理完了</remarks>
        private const string CONTROLLER_NAME_CONFIRM = "SCRN0004";

        /// <summary>アクション名：初期表示</summary>
        /// <remarks>アクション名：初期表示</remarks>
        private const string ACTION_NAME_INDEX = "Index";

        #endregion

        #region === フィールド ===

        /// <summary>社員登録Helper</summary>
        /// <remarks>社員登録Helper</remarks>
        private readonly IEV0002Helper _ev0002Helper = null;

        #endregion

        #region === コンストラクタ ===

        /// <summary>
        /// コンストラクタ
        /// </summary>
        /// <remarks>
        /// DIコンテナからインスタンスの取得
        /// </remarks>
        /// <param name="ev0002Helper">EV0002Helper</param>
        public SCRN0002Controller(IEV0002Helper ev0002Helper)
        {
            _ev0002Helper = ev0002Helper;
        }

        #endregion

        #region === 初期表示 ===

        /// <summary>
        /// 初期表示
        /// </summary>
        /// <remarks>
        /// イベント名：社員登録画面初期表示
        /// </remarks>
        /// <returns>ActionResult</returns>
        [Route("")]
        [HttpPost]
        public IActionResult Index()
        {
            var viewModelDto = _ev0002Helper.Init();
            return View(viewModelDto);
        }

        #endregion

        #region === 新規登録 ===

        /// <summary>
        /// 新規登録
        /// </summary>
        /// <remarks>
        /// イベント名：新規登録ボタン押下
        /// </remarks>
        /// <param name="request">request</param>
        /// <returns>ActionResult</returns>
        [Route("execute")]
        [HttpPost]
        public IActionResult Execute(SCRN0002Request request)
        {
            // ModelStateを格納
            request.ModelStateDictionary = ModelState;

            var viewModelDto = _ev0002Helper.Entry(request);
            if (viewModelDto.ErrorMessageList.Any())
            {
                return View(ACTION_NAME_INDEX, viewModelDto);
            }

            return View(ACTION_NAME_INDEX, CONTROLLER_NAME_CONFIRM);
        }

        #endregion

        #region === 戻る処理 ===

        /// <summary>
        /// 戻る処理
        /// </summary>
        /// <remarks>
        /// イベント名：戻るボタン押下
        /// </remarks>
        /// <returns></returns>
        [Route("back")]
        [HttpGet]
        public IActionResult Back()
        {
            return RedirectToAction(ACTION_NAME_INDEX, CONTROLLER_NAME_MENU);
        }

        #endregion
    }
}

EmployeeManegementApp/EmployeeManagementWebUI/Controllers/SCRN0003/SCRN0003Controller.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EmployeeManagementWebUI.Controllers.SCRN0003
{
    /// <summary>
    /// 社員照会・更新画面　コントローラー
    /// </summary>
    /// <remarks>
    /// 社員照会・更新画面　コントローラー
    /// </remarks>
    [Route("/employee/update")]
    public class SCRN0003Controller : Controller
    {
        #region === コンストラクタ ===

        public SCRN0003Controller()
        {
        }

        #endregion

        #region === 初期表示 ===

        /// <summary>
        /// 初期表示
        /// </summary>
        /// <remarks>
        /// イベント社員照会・更新画面初期表示：
        /// </remarks>
        /// <returns>ActionResult</returns>
        [Route("")]
        [HttpPost]
        public IActionResult Index()
        {
            return View();
        }

        #endregion

        #region === 更新処理 ===

        #endregion

        #region === 削除処理 ===

        #endregion

        #region === 戻る処理 ===

        #endregion
    }
}

EmployeeManegementApp/EmployeeManagementWebUI/Controllers/SCRN9999/SCRN9999Controller.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EmployeeManagementWebUI.Controllers.SCRN9999
{
    public class SCRN9999Controller : Controller
    {
        [Route("/error")]
        [HttpGet]
        [HttpPost]
        public IActionResult Error()
        {
            return View();
        }
    }
}

EmployeeManegementApp/EmployeeManagementWebUI/Views/SCRN0000/Index.cshtml
@*
    社員管理システムTOP画面
*@
@{
    ViewData["Title"] = "社員管理システム TOP";
}

<h2>@ViewData["Title"]</h2>

EmployeeManegementApp/EmployeeManagementWebUI/Views/SCRN0001/Index.cshtml
@*
    社員管理システム　メニュー画面
*@

@{
    ViewData["Title"] = "メニュー";
}

@model EmployeeManagementWebUI.ViewModel.SCRN0001.SCRN0001ViewModelDTO;

<h2>@ViewData["Title"]</h2>

<div>
    <fieldset>
        @foreach (var displayItem in Model.ErrorMessageList)
        {
            @Html.Label(displayItem.MessageID, displayItem.DisplayForMessage)<br />
        }
    </fieldset>
</div>

@using (Html.BeginForm("Index", "SCRN0002", FormMethod.Post))
{
    <button>社員登録</button>
}

<br/>

@using (Html.BeginForm("Index", "SCRN0003", FormMethod.Post))
{
    <label>社員ID</label>
    <br/>
    
    @Html.TextBoxFor(model => model.EmployeeID);
    <br/>

    <button>社員照会・更新</button>
}

EmployeeManegementApp/EmployeeManagementWebUI/Views/SCRN0002/Index.cshtml
@*
    社員登録画面
*@

@model EmployeeManagementWebUI.ViewModel.SCRN0002.SCRN0002ViewModelDTO;

@{
    ViewData["Title"] = "社員登録";
}

<h2>@ViewData["Title"]</h2>

<link rel="stylesheet" href="~/css/SCRN0002/SCRN0002.css">

<!-- エラーメッセージエリア -->
<div class="error-message-area">
    <fieldset>
        @foreach (var displayItem in Model.ErrorMessageList)
        {
            @Html.Label(displayItem.MessageID, displayItem.DisplayForMessage) <br />
        }
    </fieldset>
</div>

<!-- 社員情報入力From -->
<div class="input-group">

    @using (Html.BeginForm("Execute", "SCRN0002", FormMethod.Post, new { id = "form_employee_insert_info" }))
    {
        <table class="employeeInfo-input-area">
            <tr>
                <th>社員ID</th>
                <td colspan="2">
                    @Html.TextBoxFor(model => model.EmployeeID)
                </td>
            </tr>
            <tr>
                <th>所属部署</th>
                <td colspan="2">
                    @Html.DropDownListFor(
                         model => model.SelectedDepartmentCD,
                         new SelectList(Model.DepartmentPullDownList, "ItemValue", "ItemNameForDisplay"))
                </td>
            </tr>
            <tr>
                <th>役職</th>
                <td colspan="2">
                    @Html.DropDownListFor(
                         model => model.SelectedPositionCD,
                         new SelectList(Model.PositionPullDownList, "ItemValue", "ItemNameForDisplay"))
                </td>
            </tr>
            <tr>
                <th>氏名</th>
                <td colspan="2">
                    @Html.TextBoxFor(model => model.EmployeeName)
                </td>
            </tr>
            <tr>
                <th>性別</th>
                <td>
                    @Html.RadioButtonFor(
                        model => model.SelectedGenderCD, "01")
                </td>
                <td>
                    外国籍
                    @Html.CheckBoxFor(model => model.IsForeignNationality)
                </td>
            </tr>
            <tr>
                <th>生年月日</th>
                <td colspan="2">
                    @Html.TextBoxFor(model => model.Birthday)
                </td>
            </tr>
            <tr>
                <th>基本給料</th>
                <td colspan="2">
                    @Html.TextBoxFor(model => model.BaseSalary)
                    <label style="font-size:10px">(千円)</label>
                </td>
            </tr>
            <tr>
                <th>メモ</th>
                <td colspan="2">
                    @Html.TextAreaFor(model => model.Memo)
                </td>
            </tr>
        </table>
    }
</div>

<!-- 戻るボタン押下時Form -->
@using (Html.BeginForm("Back", "SCRN0002", FormMethod.Get, new { id = "form_employee_back" }))
{
}

<div class="insert-btn-Area">
    <button type="submit" form="form_employee_insert_info">新規登録</button>
    <button type="submit" form="form_employee_back">戻る</button>
</div>


EmployeeManegementApp/EmployeeManagementWebUI/Views/SCRN0003/Index.cshtml
@*
    社員管理システム　社員照会・更新画面    
*@
@{
    ViewData["Title"] = "照会・更新";
}

<h2>@ViewData["Title"]</h2>

EmployeeManegementApp/EmployeeManagementWebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="SCRN0000" asp-action="Index">社員管理システム(研修用)</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="SCRN0001" asp-action="Index">メニュー</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - 社員管理システム(研修用) - <a asp-area="" asp-controller="SCRN0001" asp-action="Index">プライバシーポリシー</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>